### ISSUE TITLE
training on fog simulation datasets

### ISSUE THREAD

**Issue by 17BuGs** [ylwhxht/L4DR#4]
Dear author,

我尝试使用您提供的fog simulation数据集来训练L4DR，但是在验证集上的效果与论文中给出的指标不能很好地对应。我在`vod_dataset.py`中修改了`self.use_fog=1`，`self.fog_I=4`，并将`self.sim_info_path`替换为`_CVL_beta_0.200`。这是我在`fog level = 4`条件下训练出的模型指标：

> Car AP@0.70, 0.70, 0.70:
> bbox AP:36.2393, 37.5138, 33.1076
> bev  AP:41.6963, 38.3321, 34.4460
> 3d   AP:23.3377, 23.6655, 20.6604
> aos  AP:33.75, 35.98, 31.64
> Car AP_R40@0.70, 0.70, 0.70:
> bbox AP:33.0580, 35.1609, 30.0094
> bev  AP:39.5321, 36.4095, 31.3007
> 3d   AP:18.7568, 18.9421, 16.2214
> aos  AP:30.33, 33.44, 28.50
> Car AP@0.70, 0.50, 0.50:
> bbox AP:36.2393, 37.5138, 33.1076
> bev  AP:56.5059, 48.1610, 43.0019
> 3d   AP:43.0323, 42.7390, 35.2223
> aos  AP:33.75, 35.98, 31.64
> Car AP_R40@0.70, 0.50, 0.50:
> bbox AP:33.0580, 35.1609, 30.0094
> bev  AP:56.2651, 46.5806, 39.4289
> 3d   AP:40.9279, 39.1024, 33.8743
> aos  AP:30.33, 33.44, 28.50
> Pedestrian AP@0.50, 0.50, 0.50:
> bbox AP:44.9698, 44.3642, 39.7489
> bev  AP:37.1579, 36.6389, 33.5584
> 3d   AP:28.7844, 28.5246, 25.5302
> aos  AP:43.15, 41.50, 37.18
> Pedestrian AP_R40@0.50, 0.50, 0.50:
> bbox AP:42.8861, 42.6435, 38.2201
> bev  AP:34.2510, 33.5144, 30.0521
> 3d   AP:25.3636, 24.4102, 21.7367
> aos  AP:40.97, 39.41, 35.21
> Pedestrian AP@0.50, 0.25, 0.25:
> bbox AP:44.9698, 44.3642, 39.7489
> bev  AP:57.8001, 56.0685, 49.8582
> 3d   AP:54.4795, 53.0960, 47.2407
> aos  AP:43.15, 41.50, 37.18
> Pedestrian AP_R40@0.50, 0.25, 0.25:
> bbox AP:42.8861, 42.6435, 38.2201
> bev  AP:58.0170, 54.9036, 49.7708
> 3d   AP:53.4446, 51.1579, 45.2932
> aos  AP:40.97, 39.41, 35.21
> Cyclist AP@0.50, 0.50, 0.50:
> bbox AP:62.6840, 60.4740, 54.3611
> bev  AP:57.0309, 52.4074, 46.2434
> 3d   AP:38.9169, 35.5485, 33.8006
> aos  AP:62.51, 60.23, 54.15
> Cyclist AP_R40@0.50, 0.50, 0.50:
> bbox AP:64.0400, 58.9724, 53.9712
> bev  AP:55.2764, 50.7206, 45.9953
> 3d   AP:36.4385, 34.1779, 30.4764
> aos  AP:63.83, 58.72, 53.73
> Cyclist AP@0.50, 0.25, 0.25:
> bbox AP:62.6840, 60.4740, 54.3611
> bev  AP:80.3171, 74.2547, 66.6210
> 3d   AP:79.6067, 73.3283, 65.9682
> aos  AP:62.51, 60.23, 54.15
> Cyclist AP_R40@0.50, 0.25, 0.25:
> bbox AP:64.0400, 58.9724, 53.9712
> bev  AP:80.5271, 75.8326, 68.8771
> 3d   AP:79.5810, 73.6063, 66.7312
> aos  AP:63.83, 58.72, 53.73

请问您是否可以指导一下问题出在哪里？

感谢！

**Comment by ylwhxht** [comment]
你好，
感谢你对我们工作的关注。
这个精度确实不太合理，我推荐从以下方面去排查：

1. 可视化一下CVL_200的点云，检查是否是对应的雾强度（如果是直接下载的则跳过）。
2. 在vod_dataset.py文件下的get_pc函数对应位置输出读取的lidar_file路径，是否真的使用了CVL_200的点云。
3. 训练的时候不要使用use_fog=1(fog_I没什么用不用管)，因为对特定强度的雾专门再训练本质上是一种数据泄露，不能说为了测试fog_level=4的性能专门只在fog_level=4的数据上训练。不管在什么fog_level上测试，训练始终都是use_fog=2采用随机采样雾模拟的方式进行训练。仅在测试的时候才调整为对应的fog_level。

**Comment by 17BuGs** [comment]
感谢您提供的建议！

我在训练的时候确实错把use_fog设置成1。不过经过修改之后，训练得到的指标仍然不合理。我不确定在数据增强的配置中是否应该使用gt_sampling，但是经过测试，问题可能主要不是在这里。下面是我使用的配置文件，能否麻烦您帮忙check一下呢？

```yaml
CLASS_NAMES: ['Car', 'Pedestrian', 'Cyclist']

DATA_CONFIG:
    _BASE_CONFIG_: cfgs/dataset_configs/Vod_fusion.yaml
    POINT_CLOUD_RANGE: [0, -25.6, -3, 51.2, 25.6, 2]
    VOD_EVA : False
    DATA_PROCESSOR:
        - NAME: mask_points_and_boxes_outside_range
          REMOVE_OUTSIDE_BOXES: True
        - NAME: sample_points
          NUM_POINTS: {
                'train': 2048,
                'test': 2048
            }
        - NAME: shuffle_points
          SHUFFLE_ENABLED: {
            'train': True,
            'test': False
          }
        
        - NAME: transform_points_to_voxels
          VOXEL_SIZE: [0.16, 0.16, 4]
          MAX_POINTS_PER_VOXEL: 32
          MAX_NUMBER_OF_VOXELS: {
            'train': 16000,
            'test': 40000
          }
          
    DATA_AUGMENTOR:
        DISABLE_AUG_LIST: ['placeholder', 'gt_sampling']
        AUG_CONFIG_LIST:
            # - NAME: gt_sampling
            #   USE_ROAD_PLANE: False
            #   DB_INFO_PATH:
            #       - vod_dbinfos_train.pkl
            #   PREPARE: {
            #      filter_by_min_points: ['Car:5', 'Pedestrian:5', 'Cyclist:5'],
            #      #filter_by_difficulty: [-1],
            #   }

            #   SAMPLE_GROUPS: ['Car:15','Pedestrian:15', 'Cyclist:15']
            #   NUM_POINT_FEATURES_L: 4
            #   NUM_POINT_FEATURES_R: 7
            #   DATABASE_WITH_FAKELIDAR: False
            #   REMOVE_EXTRA_WIDTH: [0.0, 0.0, 0.0]
            #   LIMIT_WHOLE_SCENE: False

            - NAME: random_world_flip
              ALONG_AXIS_LIST: ['x']

            - NAME: random_world_rotation
              WORLD_ROT_ANGLE: [-0.78539816, 0.78539816]

            - NAME: random_world_scaling
              WORLD_SCALE_RANGE: [0.95, 1.05]



MODEL:
    NAME: PointPillarMask

    VFE:
        NAME: MME_PillarVFE
        WITH_DISTANCE: False
        USE_ABSLOTE_XYZ: True
        USE_XYZ: True
        USE_RCS: True
        USE_VR: True
        USE_RadarSCORE: True
        USE_VR_COMP: True
        USE_TIME: True
        USE_NORM: True
        USE_ELEVATION: True
        USE_DISTANCE: False
        NUM_FILTERS: [64]
        NUM_FILTERS_Radar: [64]
      
    BACKBONE_3D:
        NAME: PointNet2MSG
        SA_CONFIG:
            USE_RAWDIM : 7
            NPOINTS: [4096, 1024, 256, 64]
            RADIUS: [[0.1, 0.5], [0.5, 1.0], [1.0, 2.0], [2.0, 4.0]]
            NSAMPLE: [[16, 32], [16, 32], [16, 32], [16, 32]]
            MLPS: [[[16, 16, 32], [32, 32, 64]],
                   [[64, 64, 128], [64, 96, 128]],
                   [[128, 196, 256], [128, 196, 256]],
                   [[256, 256, 512], [256, 384, 512]]]
        FP_MLPS: [[128, 128], [256, 256], [512, 512], [512, 512]]

    MAP_TO_BEV: 
        NAME: PointPillarScatter
        NUM_BEV_FEATURES: [64,64]
        
    POINT_HEAD:
        NAME: PointHeadPreMask
        CLS_FC: [256, 256]
        CLASS_AGNOSTIC: False
        USE_POINT_FEATURES_BEFORE_FUSION: False
        TARGET_CONFIG:
            GT_EXTRA_WIDTH: [0.2, 0.2, 0.2]
            BOX_CODER: PointResidualCoder
            BOX_CODER_CONFIG: {
                'use_mean_size': True,
                'mean_size': [
                    [3.9, 1.6, 1.56],
                    [0.8, 0.6, 1.73],
                    [1.76, 0.6, 1.73]
                ]
            }

        LOSS_CONFIG:
            LOSS_REG: WeightedSmoothL1Loss
            LOSS_WEIGHTS: {
                'point_cls_weight': 2.0,
                'code_weights': [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
            }

    BACKBONE_2D:
        NAME: BaseBEVBackbone_MGF
        LAYER_NUMS: [3, 5, 5]
        LAYER_STRIDES: [2, 2, 2]
        NUM_FILTERS: [128, 256, 512]
        UPSAMPLE_STRIDES: [1, 2, 4]
        NUM_UPSAMPLE_FILTERS: [128, 128, 128]

    DENSE_HEAD:
        NAME: AnchorHeadSingle
        CLASS_AGNOSTIC: False

        USE_DIRECTION_CLASSIFIER: True
        DIR_OFFSET: 0.78539
        DIR_LIMIT_OFFSET: 0.0
        NUM_DIR_BINS: 2

        ANCHOR_GENERATOR_CONFIG: [
            {
                'class_name': 'Car',
                'anchor_sizes': [[3.9, 1.6, 1.56]],
                'anchor_rotations': [0, 1.57],
                'anchor_bottom_heights': [-1.78],
                'align_center': False,
                'feature_map_stride': 2,
                'matched_threshold': 0.6,
                'unmatched_threshold': 0.45
            },
            {
                'class_name': 'Pedestrian',
                'anchor_sizes': [[0.8, 0.6, 1.73]],
                'anchor_rotations': [0, 1.57],
                'anchor_bottom_heights': [-0.6],
                'align_center': False,
                'feature_map_stride': 2,
                'matched_threshold': 0.5,
                'unmatched_threshold': 0.35
            },
            {
                'class_name': 'Cyclist',
                'anchor_sizes': [[1.76, 0.6, 1.73]],
                'anchor_rotations': [0, 1.57],
                'anchor_bottom_heights': [-0.6],
                'align_center': False,
                'feature_map_stride': 2,
                'matched_threshold': 0.5,
                'unmatched_threshold': 0.35
            }
        ]

        TARGET_ASSIGNER_CONFIG:
            NAME: AxisAlignedTargetAssigner
            POS_FRACTION: -1.0
            SAMPLE_SIZE: 512
            NORM_BY_NUM_EXAMPLES: False
            MATCH_HEIGHT: False
            BOX_CODER: ResidualCoder

        LOSS_CONFIG:
            LOSS_WEIGHTS: {
                'cls_weight': 1.0,
                'loc_weight': 2.0,
                'dir_weight': 0.2,
                'code_weights': [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
            }

    POST_PROCESSING:
        RECALL_THRESH_LIST: [0.3, 0.5, 0.7]
        SCORE_THRESH: 0.1
        OUTPUT_RAW_SCORE: False

        EVAL_METRIC: kitti

        NMS_CONFIG:
            MULTI_CLASSES_NMS: False
            NMS_TYPE: nms_gpu
            NMS_THRESH: 0.01
            NMS_PRE_MAXSIZE: 4096
            NMS_POST_MAXSIZE: 500


OPTIMIZATION:
    BATCH_SIZE_PER_GPU: 8
    NUM_EPOCHS: 30

    OPTIMIZER: adam_onecycle
    LR: 0.001
    WEIGHT_DECAY: 0.01
    MOMENTUM: 0.9

    MOMS: [0.95, 0.85]
    PCT_START: 0.4
    DIV_FACTOR: 10
    DECAY_STEP_LIST: [35, 45]
    LR_DECAY: 0.1
    LR_CLIP: 0.0000001

    LR_WARMUP: False
    WARMUP_EPOCH: 1

    GRAD_NORM_CLIP: 10
```
